// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/zeromicro/go-zero/rest"
	"github/lhh-gh/IM/internal/business/info/api/internal/svc"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/messagerecord",
				Handler: messageRecordHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/timelinesync",
				Handler: timelineSyncHandler(serverCtx),
			},
		},
	)
}
